# Generated by Django 4.2.1 on 2023-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
