# Generated by Django 4.2.1 on 2023-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_alert_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('triggered', 'triggered'), ('deleted', 'deleted')], default='created', max_length=10),
        ),
    ]
