# Generated by Django 4.2.1 on 2023-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='updated_at',
        ),
    ]
